pipeline:
  install:
    image: node:8-slim
    commands:
      - node -v
      - npm -v
      - yarn --version
      - yarn config set cache-folder .yarn-cache
      - yarn install

  linting:
    image: node:8-slim
    commands:
      - yarn lint

  typescript:
    image: node:8-slim
    commands:
      - yarn tsc
  publish:
    image: plugins/docker
    repo: goharbor.erxes.io/${DRONE_REPO_OWNER}/${DRONE_REPO_NAME}
    registry: goharbor.erxes.io
    dockerfile: Dockerfile
    secrets: [ docker_username, docker_password ]
    tags:
      - ${DRONE_BRANCH}-latest
      - latest-${DRONE_COMMIT}
    when:
      branch: develop
      event: push
      status: success
