version: "3.3"
networks:
  erxes:
    driver: bridge
services:
  coreui:
    image: erxes/erxes:federation
    container_name: coreui
    restart: unless-stopped
    environment:
      REACT_APP_CDN_HOST: https://w.office.erxes.io
      REACT_APP_API_URL: https://api.office.erxes.io
      REACT_APP_DASHBOARD_URL: https://office.erxes.io/dashboard/front
      REACT_APP_API_SUBSCRIPTION_URL: wss://api.office.erxes.io/graphql
      NGINX_HOST: office.erxes.io
      NODE_ENV: production
      REACT_APP_FILE_UPLOAD_MAX_SIZE: 524288000
    ports:
      - 127.0.0.1:3000:80
    volumes:
      - ./plugins.js:/usr/share/nginx/html/js/plugins.js
      - ./plugin-uis:/usr/share/nginx/html/js/plugins
    networks:
      - erxes
  core:
    image: erxes/core:federation
    container_name: plugin-core-api
    restart: unless-stopped
    environment:
      PORT: "3300"
      JWT_TOKEN_SECRET: D}B:3;QHW=/9SUfw-R?XPI?ymd}ZS$$
      API_DOMAIN: https://api.office.erxes.io
      MAIN_APP_DOMAIN: https://office.erxes.io
      MONGO_URL: mongodb://erxes:kpnt4Qzrazxxqw13eaeSFU@mongo:27017/erxes_office?authSource=admin&replicaSet=rs0
      EMAIL_VERIFIER_ENDPOINT: https://email-verifier.erxes.io
      ENABLED_SERVICES_PATH: /data/enabled-services.js
      DEBUG: erxes*
      NODE_ENV: production
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: pXwPM2Gz12dM9TKzsdwkYawk9
      RABBITMQ_HOST: amqp://erxes:kF65qZDw12PJM9awdjkw82bCLW@rabbitmq:5672/office
      ELASTICSEARCH_URL: http://elasticsearch:9200
    volumes:
      - ./enabled-services.js:/data/enabled-services.js
    ports:
      - 127.0.0.1:3300:3300
    networks:
      - erxes
  gateway:
    image: erxes/gateway:federation
    container_name: gateway
    restart: unless-stopped
    environment:
      PORT: "4000"
      JWT_TOKEN_SECRET: D}B:3;QHW=/9SUfw-R?XPI?ymd}ZS$$
      MAIN_APP_DOMAIN: https://office.erxes.io
      API_DOMAIN: http://core:3300
      WIDGETS_DOMAIN: https://w.office.erxes.io
      CLIENT_PORTAL_DOMAINS: https://culture.erxes.io,https://culture.erxes.mn,https://help.erxes.io,https://back.erxes.mn
      MONGO_URL: mongodb://erxes:kpnt4Qzrazxxqw13eaeSFU@mongo:27017/erxes_office?authSource=admin&replicaSet=rs0
      DEBUG: erxes*
      NODE_ENV: production
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: pXwPM2Gz12dM9TKzsdwkYawk9
      RABBITMQ_HOST: amqp://erxes:kF65qZDw12PJM9awdjkw82bCLW@rabbitmq:5672/office
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ENABLED_SERVICES_PATH: /data/enabled-services.js
    volumes:
      - ./enabled-services.js:/data/enabled-services.js
    ports:
      - 127.0.0.1:4000:4000
    networks:
      - erxes
  worker:
    image: erxes/workers:federation
    container_name: plugin-worker-api
    restart: unless-stopped
    environment:
      PORT: "3700"
      JWT_TOKEN_SECRET: D}B:3;QHW=/9SUfw-R?XPI?ymd}ZS$$
      DEBUG: erxes*
      NODE_ENV: production
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: pXwPM2Gz12dM9TKzsdwkYawk9
      RABBITMQ_HOST: amqp://erxes:kF65qZDw12PJM9awdjkw82bCLW@rabbitmq:5672/office
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ENABLED_SERVICES_PATH: /data/enabled-services.js
    volumes:
      - ./enabled-services.js:/data/enabled-services.js
    networks:
      - erxes
  essyncer:
    image: erxes/erxes-essyncer:federation
    container_name: essyncer
    restart: unless-stopped
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      MONGO_URL: mongodb://erxes:kpnt4Qzrazxxqw13eaeSFU@mongo:27017/erxes_office?authSource=admin&replicaSet=rs0
    volumes:
      - /essyncerData:/data/essyncerData
    networks:
      - erxes
  widgets:
    image: erxes/erxes-widgets:federation
    container_name: widgets
    restart: unless-stopped
    environment:
      PORT: "3200"
      ROOT_URL: https://w.office.erxes.io
      API_URL: https://api.office.erxes.io
      API_SUBSCRIPTIONS_URL: wss://api.office.erxes.io/graphql
    ports:
      - 127.0.0.1:3200:3200
    networks:
      - erxes
  dashboard:
    image: erxes/dashboard:federation
    container_name: plugin-dashboard-api
    restart: unless-stopped
    environment:
      PORT: "3800"
      JWT_TOKEN_SECRET: D}B:3;QHW=/9SUfw-R?XPI?ymd}ZS$$
      DEBUG: erxes*
      NODE_ENV: production
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: pXwPM2Gz12dM9TKzsdwkYawk9
      RABBITMQ_HOST: amqp://erxes:kF65qZDw12PJM9awdjkw82bCLW@rabbitmq:5672/office
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ENABLED_SERVICES_PATH: /data/enabled-services.js
    volumes:
      - ./enabled-services.js:/data/enabled-services.js
    networks:
      - erxes
  dashboard-front:
    image: erxes/erxes-dashboard-front:develop
    container_name: dashboard-front
    restart: unless-stopped
    ports:
      - 127.0.0.1:4200:80
    environment:
      REACT_APP_API_URL: https://api.office.erxes.io
      REACT_APP_API_SUBSCRIPTION_URL: wss://api.office.erxes.io/graphql
      REACT_APP_DASHBOARD_API_URL: https://office.erxes.io/dashboard/api
      REACT_APP_DASHBOARD_API_TOKEN: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MDYyODYwNzAsImV4cCI6MTkyMTg2MjA3MH0.HP0plh7qfxF5nBREcbLPZXtElKG38272jBmz-yD3P6s
      NGINX_HOST: office.erxes.io
    networks:
      - erxes
  kibana:
    image: docker.elastic.co/kibana/kibana:7.6.0
    container_name: kibana
    ports:
      - 127.0.0.1:5601:5601
    networks:
      - erxes
  mongo:
    hostname: mongo
    image: mongo:4.0.20
    container_name: mongo
    ports:
      - 127.0.0.1:27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: erxes
      MONGO_INITDB_ROOT_PASSWORD: kpnt4Qzrazxxqw13eaeSFU
    networks:
      - erxes
    volumes:
      - ./mongodata:/data/db
    command:
      - --replSet
      - rs0
      - --bind_ip_all
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.8.0
    container_name: elasticsearch
    environment:
      discovery.type: single-node
    ports:
      - 127.0.0.1:9200:9200
    networks:
      - erxes
    volumes:
      - ./elasticsearchData:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
  redis:
    image: redis:5.0.5
    container_name: redis
    restart: always
    command: redis-server --appendonly yes --requirepass pXwPM2Gz12dM9TKzsdwkYawk9
    ports:
      - 127.0.0.1:6379:6379
    networks:
      - erxes
    volumes:
      - ./redisdata:/data
  rabbitmq:
    image: rabbitmq:3.7.17-management
    container_name: rabbitmq
    restart: unless-stopped
    hostname: rabbitmq
    environment:
      RABBITMQ_VM_MEMORY_HIGH_WATERMARK: 2048MiB
      RABBITMQ_ERLANG_COOKIE: dzw3YkCpZcc2cNWmN9VPVEZc9rvCsGyZB
      RABBITMQ_DEFAULT_USER: erxes
      RABBITMQ_DEFAULT_PASS: kF65qZDw12PJM9awdjkw82bCLW
      RABBITMQ_DEFAULT_VHOST: office
    ports:
      - 127.0.0.1:15672:15672
    networks:
      - erxes
    volumes:
      - ./rabbitmq-data:/var/lib/rabbitmq
  plugin_cards_api:
    container_name: plugin-cards-api
    image: erxes/plugin-cards-api:federation
    environment:
      PORT: undefined
      API_MONGO_URL: mongodb://erxes:kpnt4Qzrazxxqw13eaeSFU@mongo:27017/erxes_office?authSource=admin&replicaSet=rs0
      MONGO_URL: mongodb://erxes:kpnt4Qzrazxxqw13eaeSFU@mongo:27017/erxes_office?authSource=admin&replicaSet=rs0
      DEBUG: erxes*
      NODE_ENV: production
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: pXwPM2Gz12dM9TKzsdwkYawk9
      RABBITMQ_HOST: amqp://erxes:kF65qZDw12PJM9awdjkw82bCLW@rabbitmq:5672/office
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ENABLED_SERVICES_PATH: /data/enabled-services.js
    volumes:
      - ./enabled-services.js:/data/enabled-services.js
    networks:
      - erxes
  plugin_contacts_api:
    container_name: plugin-contacts-api
    image: erxes/plugin-contacts-api:federation
    environment:
      PORT: undefined
      API_MONGO_URL: mongodb://erxes:kpnt4Qzrazxxqw13eaeSFU@mongo:27017/erxes_office?authSource=admin&replicaSet=rs0
      MONGO_URL: mongodb://erxes:kpnt4Qzrazxxqw13eaeSFU@mongo:27017/erxes_office?authSource=admin&replicaSet=rs0
      DEBUG: erxes*
      NODE_ENV: production
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: pXwPM2Gz12dM9TKzsdwkYawk9
      RABBITMQ_HOST: amqp://erxes:kF65qZDw12PJM9awdjkw82bCLW@rabbitmq:5672/office
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ENABLED_SERVICES_PATH: /data/enabled-services.js
    volumes:
      - ./enabled-services.js:/data/enabled-services.js
    networks:
      - erxes
  plugin_engages_api:
    container_name: plugin-engages-api
    image: erxes/plugin-engages-api:federation
    environment:
      PORT: undefined
      API_MONGO_URL: mongodb://erxes:kpnt4Qzrazxxqw13eaeSFU@mongo:27017/erxes_office?authSource=admin&replicaSet=rs0
      MONGO_URL: mongodb://erxes:kpnt4Qzrazxxqw13eaeSFU@mongo:27017/erxes_office?authSource=admin&replicaSet=rs0
      DEBUG: erxes*
      NODE_ENV: production
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: pXwPM2Gz12dM9TKzsdwkYawk9
      RABBITMQ_HOST: amqp://erxes:kF65qZDw12PJM9awdjkw82bCLW@rabbitmq:5672/office
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ENABLED_SERVICES_PATH: /data/enabled-services.js
    volumes:
      - ./enabled-services.js:/data/enabled-services.js
    networks:
      - erxes
  plugin_inbox_api:
    container_name: plugin-inbox-api
    image: erxes/plugin-inbox-api:federation
    environment:
      PORT: undefined
      API_MONGO_URL: mongodb://erxes:kpnt4Qzrazxxqw13eaeSFU@mongo:27017/erxes_office?authSource=admin&replicaSet=rs0
      MONGO_URL: mongodb://erxes:kpnt4Qzrazxxqw13eaeSFU@mongo:27017/erxes_office?authSource=admin&replicaSet=rs0
      DEBUG: erxes*
      NODE_ENV: production
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: pXwPM2Gz12dM9TKzsdwkYawk9
      RABBITMQ_HOST: amqp://erxes:kF65qZDw12PJM9awdjkw82bCLW@rabbitmq:5672/office
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ENABLED_SERVICES_PATH: /data/enabled-services.js
    volumes:
      - ./enabled-services.js:/data/enabled-services.js
    networks:
      - erxes
  plugin_internalnotes_api:
    container_name: plugin-internalnotes-api
    image: erxes/plugin-internalnotes-api:federation
    environment:
      PORT: undefined
      API_MONGO_URL: mongodb://erxes:kpnt4Qzrazxxqw13eaeSFU@mongo:27017/erxes_office?authSource=admin&replicaSet=rs0
      MONGO_URL: mongodb://erxes:kpnt4Qzrazxxqw13eaeSFU@mongo:27017/erxes_office?authSource=admin&replicaSet=rs0
      DEBUG: erxes*
      NODE_ENV: production
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: pXwPM2Gz12dM9TKzsdwkYawk9
      RABBITMQ_HOST: amqp://erxes:kF65qZDw12PJM9awdjkw82bCLW@rabbitmq:5672/office
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ENABLED_SERVICES_PATH: /data/enabled-services.js
    volumes:
      - ./enabled-services.js:/data/enabled-services.js
    networks:
      - erxes
  plugin_knowledgebase_api:
    container_name: plugin-knowledgebase-api
    image: erxes/plugin-knowledgebase-api:federation
    environment:
      PORT: undefined
      API_MONGO_URL: mongodb://erxes:kpnt4Qzrazxxqw13eaeSFU@mongo:27017/erxes_office?authSource=admin&replicaSet=rs0
      MONGO_URL: mongodb://erxes:kpnt4Qzrazxxqw13eaeSFU@mongo:27017/erxes_office?authSource=admin&replicaSet=rs0
      DEBUG: erxes*
      NODE_ENV: production
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: pXwPM2Gz12dM9TKzsdwkYawk9
      RABBITMQ_HOST: amqp://erxes:kF65qZDw12PJM9awdjkw82bCLW@rabbitmq:5672/office
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ENABLED_SERVICES_PATH: /data/enabled-services.js
    volumes:
      - ./enabled-services.js:/data/enabled-services.js
    networks:
      - erxes
  plugin_notifications_api:
    container_name: plugin-notifications-api
    image: erxes/plugin-notifications-api:federation
    environment:
      PORT: undefined
      API_MONGO_URL: mongodb://erxes:kpnt4Qzrazxxqw13eaeSFU@mongo:27017/erxes_office?authSource=admin&replicaSet=rs0
      MONGO_URL: mongodb://erxes:kpnt4Qzrazxxqw13eaeSFU@mongo:27017/erxes_office?authSource=admin&replicaSet=rs0
      DEBUG: erxes*
      NODE_ENV: production
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: pXwPM2Gz12dM9TKzsdwkYawk9
      RABBITMQ_HOST: amqp://erxes:kF65qZDw12PJM9awdjkw82bCLW@rabbitmq:5672/office
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ENABLED_SERVICES_PATH: /data/enabled-services.js
    volumes:
      - ./enabled-services.js:/data/enabled-services.js
    networks:
      - erxes
  plugin_products_api:
    container_name: plugin-products-api
    image: erxes/plugin-products-api:federation
    environment:
      PORT: undefined
      API_MONGO_URL: mongodb://erxes:kpnt4Qzrazxxqw13eaeSFU@mongo:27017/erxes_office?authSource=admin&replicaSet=rs0
      MONGO_URL: mongodb://erxes:kpnt4Qzrazxxqw13eaeSFU@mongo:27017/erxes_office?authSource=admin&replicaSet=rs0
      DEBUG: erxes*
      NODE_ENV: production
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: pXwPM2Gz12dM9TKzsdwkYawk9
      RABBITMQ_HOST: amqp://erxes:kF65qZDw12PJM9awdjkw82bCLW@rabbitmq:5672/office
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ENABLED_SERVICES_PATH: /data/enabled-services.js
    volumes:
      - ./enabled-services.js:/data/enabled-services.js
    networks:
      - erxes
  plugin_forms_api:
    container_name: plugin-forms-api
    image: erxes/plugin-forms-api:federation
    environment:
      PORT: undefined
      API_MONGO_URL: mongodb://erxes:kpnt4Qzrazxxqw13eaeSFU@mongo:27017/erxes_office?authSource=admin&replicaSet=rs0
      MONGO_URL: mongodb://erxes:kpnt4Qzrazxxqw13eaeSFU@mongo:27017/erxes_office?authSource=admin&replicaSet=rs0
      DEBUG: erxes*
      NODE_ENV: production
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: pXwPM2Gz12dM9TKzsdwkYawk9
      RABBITMQ_HOST: amqp://erxes:kF65qZDw12PJM9awdjkw82bCLW@rabbitmq:5672/office
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ENABLED_SERVICES_PATH: /data/enabled-services.js
    volumes:
      - ./enabled-services.js:/data/enabled-services.js
    networks:
      - erxes
  plugin_segments_api:
    container_name: plugin-segments-api
    image: erxes/plugin-segments-api:federation
    environment:
      PORT: undefined
      API_MONGO_URL: mongodb://erxes:kpnt4Qzrazxxqw13eaeSFU@mongo:27017/erxes_office?authSource=admin&replicaSet=rs0
      MONGO_URL: mongodb://erxes:kpnt4Qzrazxxqw13eaeSFU@mongo:27017/erxes_office?authSource=admin&replicaSet=rs0
      DEBUG: erxes*
      NODE_ENV: production
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: pXwPM2Gz12dM9TKzsdwkYawk9
      RABBITMQ_HOST: amqp://erxes:kF65qZDw12PJM9awdjkw82bCLW@rabbitmq:5672/office
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ENABLED_SERVICES_PATH: /data/enabled-services.js
    volumes:
      - ./enabled-services.js:/data/enabled-services.js
    networks:
      - erxes
  plugin_tags_api:
    container_name: plugin-tags-api
    image: erxes/plugin-tags-api:federation
    environment:
      PORT: undefined
      API_MONGO_URL: mongodb://erxes:kpnt4Qzrazxxqw13eaeSFU@mongo:27017/erxes_office?authSource=admin&replicaSet=rs0
      MONGO_URL: mongodb://erxes:kpnt4Qzrazxxqw13eaeSFU@mongo:27017/erxes_office?authSource=admin&replicaSet=rs0
      DEBUG: erxes*
      NODE_ENV: production
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: pXwPM2Gz12dM9TKzsdwkYawk9
      RABBITMQ_HOST: amqp://erxes:kF65qZDw12PJM9awdjkw82bCLW@rabbitmq:5672/office
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ENABLED_SERVICES_PATH: /data/enabled-services.js
    volumes:
      - ./enabled-services.js:/data/enabled-services.js
    networks:
      - erxes
  plugin_logs_api:
    container_name: plugin-logs-api
    image: erxes/plugin-logs-api:federation
    environment:
      PORT: undefined
      API_MONGO_URL: mongodb://erxes:kpnt4Qzrazxxqw13eaeSFU@mongo:27017/erxes_office?authSource=admin&replicaSet=rs0
      MONGO_URL: mongodb://erxes:kpnt4Qzrazxxqw13eaeSFU@mongo:27017/erxes_office_logs?authSource=admin&replicaSet=rs0
      DEBUG: erxes*
      NODE_ENV: production
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: pXwPM2Gz12dM9TKzsdwkYawk9
      RABBITMQ_HOST: amqp://erxes:kF65qZDw12PJM9awdjkw82bCLW@rabbitmq:5672/office
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ENABLED_SERVICES_PATH: /data/enabled-services.js
    volumes:
      - ./enabled-services.js:/data/enabled-services.js
    networks:
      - erxes
  client-portal:
    image: erxes/erxes-client-portal:ci_implement
    container_name: client-portal
    environment:
      REACT_APP_API_URL: https://api.office.erxes.io
      REACT_APP_TOPIC_ID: 7gS2nbdE4vnf6vSiE
      NGINX_HOST: erxes.io
    ports:
      - 127.0.0.1:4400:80
    networks:
      - erxes
  cp:
    image: erxes/erxes-cp:next
    container_name: erxes-cp
    environment:
      JWT_TOKEN_SECRET: asjdalksjd123k123jk190239asd
      MONGO_URL: mongodb://erxes:kpnt4Qzrazxxqw13eaeSFU@mongo:27017/erxes_client_portal?authSource=admin&replicaSet=rs0
      MAIN_API_DOMAIN: https://api.office.erxes.io
      REACT_APP_MAIN_API_DOMAIN: https://api.office.erxes.io
      REACT_APP_NEXT_PUBLIC_MAIN_API_DOMAIN: https://cp.office.erxes.io/api
      REACT_APP_CLIENT_PORTAL_CONFIG_ID: hTXArb3i2Xm2hoNnF
    ports:
      - 127.0.0.1:5300:3000
    networks:
      - erxes
