version: "3"
services:
  erxes:
    image: erxes/erxes:latest
    # command: bash -c "yarn install && yarn start"
    command: yarn start
    ports:
      - "3000:3000"
    volumes:
      - ..:/usr/src/erxes
      - /usr/src/erxes/node_modules
    depends_on:
      - "erxes-app-api"

  erxes-app-api:
    image: erxes/erxes-app-api:latest
    command: bash -c "yarn loadInitialData && yarn dev"
    ports:
      - "3300:3300"
    volumes:
      - ../../erxes-app-api:/usr/src/erxes-app-api
      - /usr/src/erxes-app-api/node_modules
    depends_on:
      - "mongo"
      - "redis"
    environment:
      REDIS_HOST: redis

  erxes-api:
    image: erxes/erxes-api:latest
    command: yarn dev
    ports:
      - "3100:3100"
    volumes:
      - ../../erxes-api:/usr/src/erxes-api
      - /usr/src/erxes-api/node_modules
    depends_on:
      - "mongo"
      - "erxes-app-api"
    links:
      - "mongo"
      - "erxes-app-api"

  erxes-widgets:
    image: erxes/erxes-widgets:latest
    command: yarn dev
    ports:
      - "3200:3200"
    volumes:
      - ../../erxes-widgets:/usr/src/erxes-widgets
      - /usr/src/erxes-widgets/node_modules

  mongo:
    image: "mongo"
    ports:
      - "27017:27017"
    # volumes:
    #   - ./data/db:/data/db

  redis:
    image: "redis:alpine"
