name: Plugin UI CI

on:
  push:
    branches:
      - '**'
    paths:
      - 'packages/plugin-card-ui'
      - '.github/workflows/plugin-ui.yaml'

jobs:
  ui:
    runs-on: ubuntu-18.04

    steps:
      - name: Use Node.js 14.18.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.18.x

      - uses: actions/checkout@v2

      - name: Build
        run: |
          yarn install --frozen-lockfile
          cp packages/ui-plugin-template/.erxes packages/plugin-card-ui/.erxes
          cd packages/plugin-card-ui
          yarn install-deps
          yarn build

      - name: Deploy
        run: aws s3 sync ./YOUR-BUILD-DIR s3://YOUR-BUCKET-NAME