name: Publish Release
on:
  push:
    branches:
      - dev
      - master
jobs:
  release:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Get release version
        id: get_release_version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}
      - name: core
        if: github.event_name == 'push' && ( github.ref == 'refs/heads/master' ||
          github.ref == 'refs/heads/dev'  )
        run: >
          echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{
          secrets.DOCKERHUB_USERNAME }} --password-stdin 

          docker image pull erxes/core:dev 

          docker tag erxes/core:dev erxes/core:master 

          docker push erxes/core:master 
