name: Publish Release
on:
  push:
    branches:
      - dev
      - master
jobs:
  release:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Get release version
        id: get_release_version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      - name: inbox ui
        if: github.event_name == 'push' && ( github.ref == 'refs/heads/master' ||
          github.ref == 'refs/heads/dev'  )
        run: aws s3 sync s3://erxes-dev-plugins/uis/plugin-inbox-ui
          s3://erxes-release-plugins/uis/plugin-inbox-ui/0.1/
      - name: automations ui
        if: github.event_name == 'push' && ( github.ref == 'refs/heads/master' ||
          github.ref == 'refs/heads/dev'  )
        run: aws s3 sync s3://erxes-dev-plugins/uis/plugin-automations-ui
          s3://erxes-release-plugins/uis/plugin-automations-ui/0.1/
      - name: cards ui
        if: github.event_name == 'push' && ( github.ref == 'refs/heads/master' ||
          github.ref == 'refs/heads/dev'  )
        run: aws s3 sync s3://erxes-dev-plugins/uis/plugin-cards-ui
          s3://erxes-release-plugins/uis/plugin-cards-ui/0.1/
      - name: clientportal ui
        if: github.event_name == 'push' && ( github.ref == 'refs/heads/master' ||
          github.ref == 'refs/heads/dev'  )
        run: aws s3 sync s3://erxes-dev-plugins/uis/plugin-clientportal-ui
          s3://erxes-release-plugins/uis/plugin-clientportal-ui/0.1/
      - name: contacts ui
        if: github.event_name == 'push' && ( github.ref == 'refs/heads/master' ||
          github.ref == 'refs/heads/dev'  )
        run: aws s3 sync s3://erxes-dev-plugins/uis/plugin-contacts-ui
          s3://erxes-release-plugins/uis/plugin-contacts-ui/0.1/
      - name: dashboard ui
        if: github.event_name == 'push' && ( github.ref == 'refs/heads/master' ||
          github.ref == 'refs/heads/dev'  )
        run: aws s3 sync s3://erxes-dev-plugins/uis/plugin-dashboard-ui
          s3://erxes-release-plugins/uis/plugin-dashboard-ui/0.1/
      - name: emailtemplates ui
        if: github.event_name == 'push' && ( github.ref == 'refs/heads/master' ||
          github.ref == 'refs/heads/dev'  )
        run: aws s3 sync s3://erxes-dev-plugins/uis/plugin-emailtemplates-ui
          s3://erxes-release-plugins/uis/plugin-emailtemplates-ui/0.1/
      - name: engages ui
        if: github.event_name == 'push' && ( github.ref == 'refs/heads/master' ||
          github.ref == 'refs/heads/dev'  )
        run: aws s3 sync s3://erxes-dev-plugins/uis/plugin-engages-ui
          s3://erxes-release-plugins/uis/plugin-engages-ui/0.1/
      - name: forms ui
        if: github.event_name == 'push' && ( github.ref == 'refs/heads/master' ||
          github.ref == 'refs/heads/dev'  )
        run: aws s3 sync s3://erxes-dev-plugins/uis/plugin-forms-ui
          s3://erxes-release-plugins/uis/plugin-forms-ui/0.1/
      - name: integrations ui
        if: github.event_name == 'push' && ( github.ref == 'refs/heads/master' ||
          github.ref == 'refs/heads/dev'  )
        run: aws s3 sync s3://erxes-dev-plugins/uis/plugin-integrations-ui
          s3://erxes-release-plugins/uis/plugin-integrations-ui/0.1/
      - name: internalnotes ui
        if: github.event_name == 'push' && ( github.ref == 'refs/heads/master' ||
          github.ref == 'refs/heads/dev'  )
        run: aws s3 sync s3://erxes-dev-plugins/uis/plugin-internalnotes-ui
          s3://erxes-release-plugins/uis/plugin-internalnotes-ui/0.1/
      - name: knowledgebase ui
        if: github.event_name == 'push' && ( github.ref == 'refs/heads/master' ||
          github.ref == 'refs/heads/dev'  )
        run: aws s3 sync s3://erxes-dev-plugins/uis/plugin-knowledgebase-ui
          s3://erxes-release-plugins/uis/plugin-knowledgebase-ui/0.1/
      - name: logs ui
        if: github.event_name == 'push' && ( github.ref == 'refs/heads/master' ||
          github.ref == 'refs/heads/dev'  )
        run: aws s3 sync s3://erxes-dev-plugins/uis/plugin-logs-ui
          s3://erxes-release-plugins/uis/plugin-logs-ui/0.1/
      - name: notifications ui
        if: github.event_name == 'push' && ( github.ref == 'refs/heads/master' ||
          github.ref == 'refs/heads/dev'  )
        run: aws s3 sync s3://erxes-dev-plugins/uis/plugin-notifications-ui
          s3://erxes-release-plugins/uis/plugin-notifications-ui/0.1/
      - name: webhooks ui
        if: github.event_name == 'push' && ( github.ref == 'refs/heads/master' ||
          github.ref == 'refs/heads/dev'  )
        run: aws s3 sync s3://erxes-dev-plugins/uis/plugin-webhooks-ui
          s3://erxes-release-plugins/uis/plugin-webhooks-ui/0.1/
      - name: products ui
        if: github.event_name == 'push' && ( github.ref == 'refs/heads/master' ||
          github.ref == 'refs/heads/dev'  )
        run: aws s3 sync s3://erxes-dev-plugins/uis/plugin-products-ui
          s3://erxes-release-plugins/uis/plugin-products-ui/0.1/
      - name: segments ui
        if: github.event_name == 'push' && ( github.ref == 'refs/heads/master' ||
          github.ref == 'refs/heads/dev'  )
        run: aws s3 sync s3://erxes-dev-plugins/uis/plugin-segments-ui
          s3://erxes-release-plugins/uis/plugin-segments-ui/0.1/
      - name: tags ui
        if: github.event_name == 'push' && ( github.ref == 'refs/heads/master' ||
          github.ref == 'refs/heads/dev'  )
        run: aws s3 sync s3://erxes-dev-plugins/uis/plugin-tags-ui
          s3://erxes-release-plugins/uis/plugin-tags-ui/0.1/
      - name: loyalties ui
        if: github.event_name == 'push' && ( github.ref == 'refs/heads/master' ||
          github.ref == 'refs/heads/dev'  )
        run: aws s3 sync s3://erxes-dev-plugins/uis/plugin-loyalties-ui
          s3://erxes-release-plugins/uis/plugin-loyalties-ui/0.1/
      - name: webbuilder ui
        if: github.event_name == 'push' && ( github.ref == 'refs/heads/master' ||
          github.ref == 'refs/heads/dev'  )
        run: aws s3 sync s3://erxes-dev-plugins/uis/plugin-webbuilder-ui
          s3://erxes-release-plugins/uis/plugin-webbuilder-ui/0.1/
