name: Publish Release
on:
  push:
    branches:
      - dev
      - master
jobs:
  release:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Get release version
        id: get_release_version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}
      - name: erxes
        if: github.event_name == 'push' && ( github.ref == 'refs/heads/master' ||
          github.ref == 'refs/heads/dev'  )
        run: >
          echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{
          secrets.DOCKERHUB_USERNAME }} --password-stdin 

          docker image pull erxes/erxes:dev 

          docker tag erxes/erxes:dev erxes/erxes:master 

          docker push erxes/erxes:master 
      - name: core
        if: github.event_name == 'push' && ( github.ref == 'refs/heads/master' ||
          github.ref == 'refs/heads/dev'  )
        run: >
          echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{
          secrets.DOCKERHUB_USERNAME }} --password-stdin 

          docker image pull erxes/core:dev 

          docker tag erxes/core:dev erxes/core:master 

          docker push erxes/core:master 
      - name: gateway
        if: github.event_name == 'push' && ( github.ref == 'refs/heads/master' ||
          github.ref == 'refs/heads/dev'  )
        run: >
          echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{
          secrets.DOCKERHUB_USERNAME }} --password-stdin 

          docker image pull erxes/gateway:dev 

          docker tag erxes/gateway:dev erxes/gateway:master 

          docker push erxes/gateway:master 
      - name: crons
        if: github.event_name == 'push' && ( github.ref == 'refs/heads/master' ||
          github.ref == 'refs/heads/dev'  )
        run: >
          echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{
          secrets.DOCKERHUB_USERNAME }} --password-stdin 

          docker image pull erxes/crons:dev 

          docker tag erxes/crons:dev erxes/crons:master 

          docker push erxes/crons:master 
      - name: workers
        if: github.event_name == 'push' && ( github.ref == 'refs/heads/master' ||
          github.ref == 'refs/heads/dev'  )
        run: >
          echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{
          secrets.DOCKERHUB_USERNAME }} --password-stdin 

          docker image pull erxes/workers:dev 

          docker tag erxes/workers:dev erxes/workers:master 

          docker push erxes/workers:master 
      - name: essyncer
        if: github.event_name == 'push' && ( github.ref == 'refs/heads/master' ||
          github.ref == 'refs/heads/dev'  )
        run: >
          echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{
          secrets.DOCKERHUB_USERNAME }} --password-stdin 

          docker image pull erxes/essyncer:dev 

          docker tag erxes/essyncer:dev erxes/essyncer:master 

          docker push erxes/essyncer:master 
      - name: widgets
        if: github.event_name == 'push' && ( github.ref == 'refs/heads/master' ||
          github.ref == 'refs/heads/dev'  )
        run: >
          echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{
          secrets.DOCKERHUB_USERNAME }} --password-stdin 

          docker image pull erxes/widgets:dev 

          docker tag erxes/widgets:dev erxes/widgets:master 

          docker push erxes/widgets:master 
      - name: client-portal
        if: github.event_name == 'push' && ( github.ref == 'refs/heads/master' ||
          github.ref == 'refs/heads/dev'  )
        run: >
          echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{
          secrets.DOCKERHUB_USERNAME }} --password-stdin 

          docker image pull erxes/client-portal:dev 

          docker tag erxes/client-portal:dev erxes/client-portal:master 

          docker push erxes/client-portal:master 
      - name: plugin-inbox-api
        if: github.event_name == 'push' && ( github.ref == 'refs/heads/master' ||
          github.ref == 'refs/heads/dev'  )
        run: >
          echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{
          secrets.DOCKERHUB_USERNAME }} --password-stdin 

          docker image pull erxes/plugin-inbox-api:dev 

          docker tag erxes/plugin-inbox-api:dev erxes/plugin-inbox-api:master 

          docker push erxes/plugin-inbox-api:master 
      - name: plugin-automations-api
        if: github.event_name == 'push' && ( github.ref == 'refs/heads/master' ||
          github.ref == 'refs/heads/dev'  )
        run: >
          echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{
          secrets.DOCKERHUB_USERNAME }} --password-stdin 

          docker image pull erxes/plugin-automations-api:dev 

          docker tag erxes/plugin-automations-api:dev erxes/plugin-automations-api:master 

          docker push erxes/plugin-automations-api:master 
      - name: plugin-cards-api
        if: github.event_name == 'push' && ( github.ref == 'refs/heads/master' ||
          github.ref == 'refs/heads/dev'  )
        run: >
          echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{
          secrets.DOCKERHUB_USERNAME }} --password-stdin 

          docker image pull erxes/plugin-cards-api:dev 

          docker tag erxes/plugin-cards-api:dev erxes/plugin-cards-api:master 

          docker push erxes/plugin-cards-api:master 
      - name: plugin-clientportal-api
        if: github.event_name == 'push' && ( github.ref == 'refs/heads/master' ||
          github.ref == 'refs/heads/dev'  )
        run: >
          echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{
          secrets.DOCKERHUB_USERNAME }} --password-stdin 

          docker image pull erxes/plugin-clientportal-api:dev 

          docker tag erxes/plugin-clientportal-api:dev erxes/plugin-clientportal-api:master 

          docker push erxes/plugin-clientportal-api:master 
      - name: plugin-contacts-api
        if: github.event_name == 'push' && ( github.ref == 'refs/heads/master' ||
          github.ref == 'refs/heads/dev'  )
        run: >
          echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{
          secrets.DOCKERHUB_USERNAME }} --password-stdin 

          docker image pull erxes/plugin-contacts-api:dev 

          docker tag erxes/plugin-contacts-api:dev erxes/plugin-contacts-api:master 

          docker push erxes/plugin-contacts-api:master 
      - name: plugin-dashboard-api
        if: github.event_name == 'push' && ( github.ref == 'refs/heads/master' ||
          github.ref == 'refs/heads/dev'  )
        run: >
          echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{
          secrets.DOCKERHUB_USERNAME }} --password-stdin 

          docker image pull erxes/plugin-dashboard-api:dev 

          docker tag erxes/plugin-dashboard-api:dev erxes/plugin-dashboard-api:master 

          docker push erxes/plugin-dashboard-api:master 
      - name: plugin-emailtemplates-api
        if: github.event_name == 'push' && ( github.ref == 'refs/heads/master' ||
          github.ref == 'refs/heads/dev'  )
        run: >
          echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{
          secrets.DOCKERHUB_USERNAME }} --password-stdin 

          docker image pull erxes/plugin-emailtemplates-api:dev 

          docker tag erxes/plugin-emailtemplates-api:dev erxes/plugin-emailtemplates-api:master 

          docker push erxes/plugin-emailtemplates-api:master 
      - name: plugin-engages-api
        if: github.event_name == 'push' && ( github.ref == 'refs/heads/master' ||
          github.ref == 'refs/heads/dev'  )
        run: >
          echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{
          secrets.DOCKERHUB_USERNAME }} --password-stdin 

          docker image pull erxes/plugin-engages-api:dev 

          docker tag erxes/plugin-engages-api:dev erxes/plugin-engages-api:master 

          docker push erxes/plugin-engages-api:master 
      - name: plugin-forms-api
        if: github.event_name == 'push' && ( github.ref == 'refs/heads/master' ||
          github.ref == 'refs/heads/dev'  )
        run: >
          echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{
          secrets.DOCKERHUB_USERNAME }} --password-stdin 

          docker image pull erxes/plugin-forms-api:dev 

          docker tag erxes/plugin-forms-api:dev erxes/plugin-forms-api:master 

          docker push erxes/plugin-forms-api:master 
      - name: plugin-integrations-api
        if: github.event_name == 'push' && ( github.ref == 'refs/heads/master' ||
          github.ref == 'refs/heads/dev'  )
        run: >
          echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{
          secrets.DOCKERHUB_USERNAME }} --password-stdin 

          docker image pull erxes/plugin-integrations-api:dev 

          docker tag erxes/plugin-integrations-api:dev erxes/plugin-integrations-api:master 

          docker push erxes/plugin-integrations-api:master 
      - name: plugin-internalnotes-api
        if: github.event_name == 'push' && ( github.ref == 'refs/heads/master' ||
          github.ref == 'refs/heads/dev'  )
        run: >
          echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{
          secrets.DOCKERHUB_USERNAME }} --password-stdin 

          docker image pull erxes/plugin-internalnotes-api:dev 

          docker tag erxes/plugin-internalnotes-api:dev erxes/plugin-internalnotes-api:master 

          docker push erxes/plugin-internalnotes-api:master 
      - name: plugin-knowledgebase-api
        if: github.event_name == 'push' && ( github.ref == 'refs/heads/master' ||
          github.ref == 'refs/heads/dev'  )
        run: >
          echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{
          secrets.DOCKERHUB_USERNAME }} --password-stdin 

          docker image pull erxes/plugin-knowledgebase-api:dev 

          docker tag erxes/plugin-knowledgebase-api:dev erxes/plugin-knowledgebase-api:master 

          docker push erxes/plugin-knowledgebase-api:master 
      - name: plugin-logs-api
        if: github.event_name == 'push' && ( github.ref == 'refs/heads/master' ||
          github.ref == 'refs/heads/dev'  )
        run: >
          echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{
          secrets.DOCKERHUB_USERNAME }} --password-stdin 

          docker image pull erxes/plugin-logs-api:dev 

          docker tag erxes/plugin-logs-api:dev erxes/plugin-logs-api:master 

          docker push erxes/plugin-logs-api:master 
      - name: plugin-notifications-api
        if: github.event_name == 'push' && ( github.ref == 'refs/heads/master' ||
          github.ref == 'refs/heads/dev'  )
        run: >
          echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{
          secrets.DOCKERHUB_USERNAME }} --password-stdin 

          docker image pull erxes/plugin-notifications-api:dev 

          docker tag erxes/plugin-notifications-api:dev erxes/plugin-notifications-api:master 

          docker push erxes/plugin-notifications-api:master 
      - name: plugin-webhooks-api
        if: github.event_name == 'push' && ( github.ref == 'refs/heads/master' ||
          github.ref == 'refs/heads/dev'  )
        run: >
          echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{
          secrets.DOCKERHUB_USERNAME }} --password-stdin 

          docker image pull erxes/plugin-webhooks-api:dev 

          docker tag erxes/plugin-webhooks-api:dev erxes/plugin-webhooks-api:master 

          docker push erxes/plugin-webhooks-api:master 
      - name: plugin-products-api
        if: github.event_name == 'push' && ( github.ref == 'refs/heads/master' ||
          github.ref == 'refs/heads/dev'  )
        run: >
          echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{
          secrets.DOCKERHUB_USERNAME }} --password-stdin 

          docker image pull erxes/plugin-products-api:dev 

          docker tag erxes/plugin-products-api:dev erxes/plugin-products-api:master 

          docker push erxes/plugin-products-api:master 
      - name: plugin-segments-api
        if: github.event_name == 'push' && ( github.ref == 'refs/heads/master' ||
          github.ref == 'refs/heads/dev'  )
        run: >
          echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{
          secrets.DOCKERHUB_USERNAME }} --password-stdin 

          docker image pull erxes/plugin-segments-api:dev 

          docker tag erxes/plugin-segments-api:dev erxes/plugin-segments-api:master 

          docker push erxes/plugin-segments-api:master 
      - name: plugin-tags-api
        if: github.event_name == 'push' && ( github.ref == 'refs/heads/master' ||
          github.ref == 'refs/heads/dev'  )
        run: >
          echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{
          secrets.DOCKERHUB_USERNAME }} --password-stdin 

          docker image pull erxes/plugin-tags-api:dev 

          docker tag erxes/plugin-tags-api:dev erxes/plugin-tags-api:master 

          docker push erxes/plugin-tags-api:master 
      - name: plugin-loyalties-api
        if: github.event_name == 'push' && ( github.ref == 'refs/heads/master' ||
          github.ref == 'refs/heads/dev'  )
        run: >
          echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{
          secrets.DOCKERHUB_USERNAME }} --password-stdin 

          docker image pull erxes/plugin-loyalties-api:dev 

          docker tag erxes/plugin-loyalties-api:dev erxes/plugin-loyalties-api:master 

          docker push erxes/plugin-loyalties-api:master 
      - name: plugin-webbuilder-api
        if: github.event_name == 'push' && ( github.ref == 'refs/heads/master' ||
          github.ref == 'refs/heads/dev'  )
        run: >
          echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{
          secrets.DOCKERHUB_USERNAME }} --password-stdin 

          docker image pull erxes/plugin-webbuilder-api:dev 

          docker tag erxes/plugin-webbuilder-api:dev erxes/plugin-webbuilder-api:master 

          docker push erxes/plugin-webbuilder-api:master 
